Fetch checksums instead of full binaries

diff --git a/release b/release
--- a/release
+++ b/release
@@ -19,39 +19,39 @@ source "logging.sh"
 source "slack.sh"
 
 preflight_checks() {
-  [[ "$GITHUB_TOKEN" ]] || {
-    fatal "No GITHUB_TOKEN available."
-  }
-  [[ "$SLACK_TOKEN" ]] || {
-    fatal "No SLACK_TOKEN available."
-  }
+	[[ "$GITHUB_TOKEN" ]] || {
+		fatal "No GITHUB_TOKEN available."
+	}
+	[[ "$SLACK_TOKEN" ]] || {
+		fatal "No SLACK_TOKEN available."
+	}
 
-  info "About to release v${VERSION} of ${PROJECT} at $COMMIT: '$COMMIT_MSG'."
-  confirm
+	info "About to release v${VERSION} of ${PROJECT} at $COMMIT: '$COMMIT_MSG'."
+	confirm
 }
 
 build_binaries() {
-  info "Building telemetry binaries.."
-  ./telemetry/build
-  info "Building secretservice binaries.."
-  ./secretservice/build
+	info "Building telemetry binaries.."
+	bash telemetry/build
+	info "Building secretservice binaries.."
+	bash secretservice/build
 }
 
 create_tag() {
-  # TODO: Verify repo is in clean state, as repo_report would see it, before tagging and releasing.
-  info "Syncing down changes from remote.."
-  git pull
-  info "Pushing any changes to remote.."
-  git push
-  info "Tagging $VERSION at $COMMIT.."
-  git tag $VERSION $COMMIT
-  git push origin --tags
+	# TODO: Verify repo is in clean state, as repo_report would see it, before tagging and releasing.
+	info "Syncing down changes from remote.."
+	git pull
+	info "Pushing any changes to remote.."
+	git push
+	info "Tagging $VERSION at $COMMIT.."
+	git tag $VERSION $COMMIT
+	git push origin --tags
 }
 
 create_release() {
-  info "Creating release.."
-  local payload
-  payload=$(cat <<EOT
+	info "Creating release.."
+	local payload
+	payload=$(cat <<EOT
 {
   "tag_name": "$VERSION",
   "name": "$VERSION",
@@ -61,38 +61,38 @@ create_release() {
 }
 EOT
 )
-  local response
-  response=$(curl -s \
-     -H "Content-type: application/json" \
-     -H "Accept: application/vnd.github.v3+json" \
-     -H "Authorization: token ${GITHUB_TOKEN}" \
-     --data "${payload}" \
-     ${GITHUB_API_URL}) 
+	local response
+	response=$(curl -s \
+	    -H "Content-type: application/json" \
+	    -H "Accept: application/vnd.github.v3+json" \
+	    -H "Authorization: token ${GITHUB_TOKEN}" \
+	    --data "${payload}" \
+	  ${GITHUB_API_URL})
 
-  debugV "Response is: ${response}"
-  local url
-  # TODO: Could dockerize release tools, since curl / jq might not be installed..
-  url=$(echo "${response}" | jq -r ".upload_url")
-  [[ "${url}" ]] && [[ "${url}" != "null" ]] || fatal "Couldn't get upload_url from Github response: ${response}"
-  debugV "URL is '${url}'"
-  export URL=${url%\{?name,label\}}
-  debugV "Stripped url is '${URL}'"
+	debugV "Response is: ${response}"
+	local url
+	# TODO: Could dockerize release tools, since curl / jq might not be installed..
+	url=$(echo "${response}" | jq -r ".upload_url")
+	[[ "${url}" ]] && [[ "${url}" != "null" ]] || fatal "Couldn't get upload_url from Github response: ${response}"
+	debugV "URL is '${url}'"
+	export URL=${url%\{?name,label\}}
+	debugV "Stripped url is '${URL}'"
 }
 
 upload() {
-  [[ $# -ne 2 ]] && fatal "usage: upload file url"
-  [[ -e ${1} ]] || fatal "No such file to upload: ${1}"
-  info "Uploading $1 to $2.."
-  local response
-  response=$(curl \
-     -H "Content-type: application/octet-stream" \
-     -H "Accept: application/vnd.github.v3+json" \
-     -H "Authorization: token $GITHUB_TOKEN" \
-     --data-binary @${1} \
-     --progress-bar \
-     "${2}?name=${1}" | tee /dev/null)
-  debugV "Upload response for $1: $response"
-  [[ ${PIPESTATUS[0]} -eq 0 ]] || fatal "Failed to upload $1"
+	[[ $# -ne 2 ]] && fatal "usage: upload file url"
+	[[ -e ${1} ]] || fatal "No such file to upload: ${1}"
+	info "Uploading $1 to $2.."
+	local response
+	response=$(curl \
+	  -H "Content-type: application/octet-stream" \
+	  -H "Accept: application/vnd.github.v3+json" \
+	  -H "Authorization: token $GITHUB_TOKEN" \
+	  --data-binary @${1} \
+	  --progress-bar \
+	  "${2}?name=${1}" | tee /dev/null)
+	debugV "Upload response for $1: $response"
+	[[ ${PIPESTATUS[0]} -eq 0 ]] || fatal "Failed to upload $1"
 }
 
 preflight_checks
@@ -107,7 +107,6 @@ upload tclient_armv7l ${URL}
 upload tserver_armv7l ${URL}
 upload gather_facts ${URL}
 
-cd -
-cd secretservice
+cd ../secretservice
 upload secretservice ${URL}
 slacksend "Released \`${PROJECT}\` v${VERSION}: ${LINK_URL}/${VERSION}"
